version: '3.8'

services:
  calculator_server:
    build: ./mcp_servers/calculator_server
    ports:
      - "8001:8000"
    volumes:
      - ./mcp_servers/calculator_server:/app
    environment:
      - LOG_LEVEL=debug

  weather_server:
    build: ./mcp_servers/weather_server
    ports:
      - "8002:8000"
    volumes:
      - ./mcp_servers/weather_server:/app
    environment:
      - LOG_LEVEL=debug

  tavily_server:
    build: ./mcp_servers/tavily_server
    ports:
      - "8003:8000"
    volumes:
      - ./mcp_servers/tavily_server:/app
    environment:
      - LOG_LEVEL=debug
      - TAVILY_API_KEY=${TAVILY_API_KEY}
